/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as RsvpRouteImport } from './routes/rsvp'
import { Route as MembersRouteImport } from './routes/members'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FeelingsRouteImport } from './routes/feelings'
import { Route as IndexRouteImport } from './routes/index'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpRoute = RsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeelingsRoute = FeelingsRouteImport.update({
  id: '/feelings',
  path: '/feelings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feelings': typeof FeelingsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRoute
  '/rsvp': typeof RsvpRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feelings': typeof FeelingsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRoute
  '/rsvp': typeof RsvpRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feelings': typeof FeelingsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRoute
  '/rsvp': typeof RsvpRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feelings' | '/gallery' | '/members' | '/rsvp' | '/teachers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feelings' | '/gallery' | '/members' | '/rsvp' | '/teachers'
  id:
    | '__root__'
    | '/'
    | '/feelings'
    | '/gallery'
    | '/members'
    | '/rsvp'
    | '/teachers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeelingsRoute: typeof FeelingsRoute
  GalleryRoute: typeof GalleryRoute
  MembersRoute: typeof MembersRoute
  RsvpRoute: typeof RsvpRoute
  TeachersRoute: typeof TeachersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp': {
      id: '/rsvp'
      path: '/rsvp'
      fullPath: '/rsvp'
      preLoaderRoute: typeof RsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feelings': {
      id: '/feelings'
      path: '/feelings'
      fullPath: '/feelings'
      preLoaderRoute: typeof FeelingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeelingsRoute: FeelingsRoute,
  GalleryRoute: GalleryRoute,
  MembersRoute: MembersRoute,
  RsvpRoute: RsvpRoute,
  TeachersRoute: TeachersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
