/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as RsvpRouteImport } from './routes/rsvp'
import { Route as MembersRouteImport } from './routes/members'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FeelingsRouteImport } from './routes/feelings'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersTeacherIdRouteImport } from './routes/teachers.$teacherId'
import { Route as MembersMemberIdRouteImport } from './routes/members.$memberId'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpRoute = RsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeelingsRoute = FeelingsRouteImport.update({
  id: '/feelings',
  path: '/feelings',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersTeacherIdRoute = TeachersTeacherIdRouteImport.update({
  id: '/$teacherId',
  path: '/$teacherId',
  getParentRoute: () => TeachersRoute,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => MembersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/feelings': typeof FeelingsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRouteWithChildren
  '/rsvp': typeof RsvpRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/members/$memberId': typeof MembersMemberIdRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/feelings': typeof FeelingsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRouteWithChildren
  '/rsvp': typeof RsvpRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/members/$memberId': typeof MembersMemberIdRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/feelings': typeof FeelingsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRouteWithChildren
  '/rsvp': typeof RsvpRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/members/$memberId': typeof MembersMemberIdRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar'
    | '/feelings'
    | '/gallery'
    | '/members'
    | '/rsvp'
    | '/teachers'
    | '/members/$memberId'
    | '/teachers/$teacherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar'
    | '/feelings'
    | '/gallery'
    | '/members'
    | '/rsvp'
    | '/teachers'
    | '/members/$memberId'
    | '/teachers/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/feelings'
    | '/gallery'
    | '/members'
    | '/rsvp'
    | '/teachers'
    | '/members/$memberId'
    | '/teachers/$teacherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarRoute: typeof AvatarRoute
  FeelingsRoute: typeof FeelingsRoute
  GalleryRoute: typeof GalleryRoute
  MembersRoute: typeof MembersRouteWithChildren
  RsvpRoute: typeof RsvpRoute
  TeachersRoute: typeof TeachersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp': {
      id: '/rsvp'
      path: '/rsvp'
      fullPath: '/rsvp'
      preLoaderRoute: typeof RsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feelings': {
      id: '/feelings'
      path: '/feelings'
      fullPath: '/feelings'
      preLoaderRoute: typeof FeelingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$teacherId': {
      id: '/teachers/$teacherId'
      path: '/$teacherId'
      fullPath: '/teachers/$teacherId'
      preLoaderRoute: typeof TeachersTeacherIdRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof MembersRoute
    }
  }
}

interface MembersRouteChildren {
  MembersMemberIdRoute: typeof MembersMemberIdRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersMemberIdRoute: MembersMemberIdRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface TeachersRouteChildren {
  TeachersTeacherIdRoute: typeof TeachersTeacherIdRoute
}

const TeachersRouteChildren: TeachersRouteChildren = {
  TeachersTeacherIdRoute: TeachersTeacherIdRoute,
}

const TeachersRouteWithChildren = TeachersRoute._addFileChildren(
  TeachersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarRoute: AvatarRoute,
  FeelingsRoute: FeelingsRoute,
  GalleryRoute: GalleryRoute,
  MembersRoute: MembersRouteWithChildren,
  RsvpRoute: RsvpRoute,
  TeachersRoute: TeachersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
